/*
 * file generated by gmock: I3Mock.hpp
 */
#ifndef I3MOCK_HPP
#define I3MOCK_HPP

#include <gmock/gmock.h>
#include "./given/I3I4.hpp"

namespace n1 {

class I3Mock : public I3
{
public:
    MOCK_METHOD((void), f1, (), (override));
};

} // namespace n1

#endif // I3MOCK_HPP

