/*
 * file generated by gmock: I4Mock.hpp
 */
#ifndef I4MOCK_HPP
#define I4MOCK_HPP

#include <gmock/gmock.h>
#include "./given/I3I4.hpp"

namespace n1 {

class I4Mock : public I4
{
public:
    MOCK_METHOD((void), f0, (bool), (override));
    MOCK_METHOD((void), f1, (), (override));
    MOCK_METHOD((Enum), f2, (), (const, override));
};

} // namespace n1

#endif // I4MOCK_HPP

