/*
 * file generated by gmock: I5Mock.hpp
 */
#ifndef I5MOCK_HPP
#define I5MOCK_HPP

#include <gmock/gmock.h>
#include "./given/I3I4.hpp"

namespace n1 {

class I5Mock : public I5
{
public:
    MOCK_METHOD((void), f0, (), (override));
};

} // namespace n1

#endif // I5MOCK_HPP

