/*
 * file generated by gmock: TMock.hpp
 */
#ifndef TMOCK_HPP
#define TMOCK_HPP

#include <gmock/gmock.h>
#include "./given/T.hpp"

namespace n {

template<typename Elem>
class TMock : public T<Elem>
{
public:
    MOCK_METHOD((int), GetSize, (), (const, override));
    MOCK_METHOD((void), Push, (const Elem &), (override));
};

} // namespace n

#endif // TMOCK_HPP

